# Generated by Django 6.0.3 on 2026-03-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_remove_organization_location_organization_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workplace_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_remarks', models.TextField()),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='organizations.placement')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/final/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('student_remarks', models.TextField(blank=True, null=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='organizations.placement')),
            ],
        ),
    ]
