# Generated by Django 6.0.3 on 2026-03-16 02:44

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.student_cv_path),
        ),
    ]
