# Generated by Django 6.0.3 on 2026-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_internshipapplication_cv_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipapplication',
            options={'ordering': ['-application_date']},
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='preferred_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
