# Generated by Django 6.0.3 on 2026-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbookentry',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='Attended Work'),
        ),
        migrations.AddField(
            model_name='supervisioncomment',
            name='is_private_to_staff',
            field=models.BooleanField(default=False, help_text='If true, student cannot see this.'),
        ),
    ]
