# Generated by Django 6.0.3 on 2026-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplacesupervisor',
            name='company_name',
        ),
        migrations.AddField(
            model_name='workplacesupervisor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicsupervisor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('ACADEMIC_SUPERVISOR', 'Academic Supervisor'), ('WORKPLACE_SUPERVISOR', 'Workplace Supervisor'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
