# Generated by Django 6.0.3 on 2026-04-15 08:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_internshipdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipdocument',
            name='file',
            field=models.FileField(upload_to='internship_docs/', validators=[users.models.validate_file_size]),
        ),
    ]
